#+TITLE: MySQL添加用户、删除用户与授权

MySql中添加用户,新建数据库,用户授权,删除用户,修改密码(注意每行后边都跟个;表示一个命令语句结束):

* 新建用户
**  登录MYSQL：
@>mysql -u root -p
@>密码
** 创建用户：
mysql> insert into mysql.user(Host,User,Password) values("localhost","test",password("1234"));
这样就创建了一个名为：test 密码为：1234 的用户。
注意：此处的"localhost"，是指该用户只能在本地登录，不能在另外一台机器上远程登录。
如果想远程登录的话，将"localhost"改为"%"，表示在任何一台电脑上都可以登录。也可以指定某台机器可以远程登录
** 然后登录一下：
mysql>exit;
@>mysql -u test -p
@>输入密码
mysql>登录成功

* 为用户授权
授权格式：grant 权限 on 数据库.* to 用户名@登录主机 identified by "密码";　
** 登录MYSQL（有ROOT权限），这里以ROOT身份登录：
@>mysql -u root -p
@>密码
** 首先为用户创建一个数据库(testDB)：
mysql>create database testDB;
** 授权test用户拥有testDB数据库的所有权限（某个数据库的所有权限）：
mysql>grant all privileges on testDB.* to test@localhost identified by '1234';
mysql>flush privileges;//刷新系统权限表
格式：grant 权限 on 数据库.* to 用户名@登录主机 identified by "密码";　
** 如果想指定部分权限给一用户，可以这样来写:
mysql>grant select,update on testDB.* to test@localhost identified by '1234';
mysql>flush privileges; //刷新系统权限表
** 授权test用户拥有所有数据库的某些权限： 　 
mysql>grant select,delete,update,create,drop on *.* to test@"%" identified by "1234";
//test用户对所有数据库都有select,delete,update,create,drop 权限。
//@"%" 表示对所有非本地主机授权，不包括localhost。（localhost地址设为127.0.0.1，如果设为真实的本地地址，不知道是否可以，没有验证。）
//对localhost授权：加上一句grant all privileges on testDB.* to test@localhost identified by '1234';即可。

 
* 删除用户
@>mysql -u root -p
@>密码
mysql>Delete FROM user Where User='test' and Host='localhost';
mysql>flush privileges;
mysql>drop database testDB; //删除用户的数据库
删除账户及权限：>drop user 用户名@'%';
　　　　　　　　>drop user 用户名@ localhost; 

* 修改指定用户密码
@>mysql -u root -p
@>密码
mysql>update mysql.user set password=password('新密码') where User="test" and Host="localhost";
mysql>flush privileges;

* 远程连接
mysql数据库的root用户出于安全考虑默认是没有远程登陆权限的，需要自己设定。
** 添加远程权限
把user表的host设置为 % 号。
** 修改配置文件
修改 /etc/mysql/my.cnf 或者 /etc/my.cnf 文件，注释bind=127.0.0.1
** 添加转发规则
iptables -I INPUT 4 -p tcp -m state --state NEW -m tcp --dport 3306 -j ACCEPT

* 常用命令 
** 显示数据库
mysql>show database;
** 切换数据库
mysql>use '数据库名';
** 列出所有表
mysql>show tables;
** 显示数据表结构
mysql>describe 表名;
** 删除数据库和数据表
mysql>drop database 数据库名;
mysql>drop table 数据表名;
