
首先需要下载adb for linux的工具包 下载地址

解压到任何地方，不要删除掉就是了

然后新建并编辑一个文件

sudo vi /etc/udev/rules.d/70-android.rules

在里面写入：

如果你的系统是10.10,或者11.04（11.10没有测试），则写入下面这句

SUBSYSTEM==”usb”, ATTR{idVendor}==”04e8“, MODE=”0666″

如果你的系统版本是10.04 就改为下面一句

SUBSYSTEM==”usb”, SYSFS{idVendor}==”04e8“, MODE=”0666″

其中红色字体未设别标识，不同厂商的标识不一样，请按照自己的手机更改，参照表如下
Manufacturer USB Vendor ID 

然后保存退出，再设置一下权限

sudo chmod a+rx /etc/udev/rules.d/70-android.rules

这时候还需要编辑一下 ~/.bashrc 文件加入adb tool的路径

vi ~/.bashrc

在末尾加入，其中红色部分就是刚下载的工具包解压的路径

export PATH=${PATH}:/home/rabbit/Documents/platform-tools

现在需要重启一下你的Ubuntu，然后USB连接手机，确保usb调试已打开，在终端下输入

adb start-server 打开服务
如果一切正常的话
输入
adb devices
就能显示出当前连接到电脑的android设备 ^_^
试试这个命令
adb shell
就能在Ubuntu上的终端执行android的shell命令了 




安卓网的一个帖子，写得不错，记下来

ADB全称Android Debug Bridge, 是android sdk里的一个工具, 用这个工具可以直接操作管理android模拟器或者真实的andriod设备(如G1手机).

它的主要功能有:


    运行设备的shell(命令行)
    管理模拟器或设备的端口映射
    计算机和设备之间上传/下载文件
    将本地apk软件安装至模拟器或android设备 



ADB是一个 客户端-服务器端 程序, 其中客户端是你用来操作的电脑, 服务器端是android设备.

先说安装方法, 电脑上需要安装客户端. 客户端包含在sdk里. 设备上不需要安装, 只需要在手机上打开选项settings-applications-development-USBdebugging.

对于Mac和Linux用户, 下载好的sdk解压后, 可以放~或者任意目录. 然后修改~/.bash_profile文件, 设置运行环境指向sdk的tools目录.
具体是打开~/.bash_profile文件(如果没有此文件也可以自行添加), 在里面加入一行:

export PATH=${PATH}:<你的sdk目录>/tools

然后就可以使用adb命令了.

嫌安装麻烦的同学其实也可以省去上面安装步骤, 直接输入完整路径来使用命令
对于windows xp用户, 需要先安装usb驱动  android_usb_windows.zip (1.33 MB) , 然后如果你只打算使用adb而不想下载整个sdk的话, 可以下载这个单独的adb工具包  adb_win.zip (571.56 KB) 下载后解压, 把里面 adb.exe 和 AdbWinApi.dll 两个文件放到系统盘的 windows/system32 文件夹里就可以了

 

ADB常用的几个命令
1. 查看设备

    adb devices 

这个命令是查看当前连接的设备, 连接到计算机的android设备或者模拟器将会列出显示

2. 安装软件

    adb install <apk文件路径> 

这个命令将指定的apk文件安装到设备上

3. 卸载软件

    adb uninstall <软件名>
    adb uninstall -k <软件名> 

如果加 -k 参数,为卸载软件但是保留配置和缓存文件.

4. 登录设备shell

    adb shell
    adb shell <command命令> 

这个命令将登录设备的shell.
后面加<command命令>将是直接运行设备命令, 相当于执行远程命令

5. 从电脑上发送文件到设备

    adb push <本地路径> <远程路径> 

用push命令可以把本机电脑上的文件或者文件夹复制到设备(手机)

6. 从设备上下载文件到电脑

    adb pull <远程路径> <本地路径> 

用pull命令可以把设备(手机)上的文件或者文件夹复制到本机电脑

7. 显示帮助信息

    adb help 

这个命令将显示帮助信息

 

 

删除Android系统Rom自带的软件

 

Android系统没有卸载Rom自带软件的功能.可能有些同学很想删除废了武功的Youtube,想删除墙那边的Twitter.

加上Android的快捷方式没法修改没法自己排序没法分页.

安装的程序太多就会发现原来找到自己想要的东西很难.

综上所述,我觉得告知各位菜鸟同学如何删除自带的程序是很有必要的一件事情.

1.确定手机root了,取得了root权限才能删除系统文件呀.

2.下载Android_db.rar,解压到%windir/%System32下.

3.手机连接数据线,在电脑上打开cmd,然后输入命令

 

adb remount

adb shell

su

执行完成之后,你会看到:

* daemon not running. starting it now *

* daemon started successfully *

4.接着就是Linux命令行模式了,输入

 

cd system/app

你会发现没啥变化,然后输入ls回车.

这时候列表显示了system/app里面的所有文件,也就是Rom集成的一些软件了.

5.开始删除吧.比如删除Youtube,他的文件名是Youtube.odex和Youtube.apk

我们要删除这2个文件,敲入以下命令:

 

rm Youtube.*

重启,Youtube已经删除掉了,注意各位同学千万不要删除你不知道是啥的东西.

 

原文链接：

http://www.hiapk.com/bbs/thread-623-1-1.html

 

指定允许AVD的内存大小：

emulator -avd avdName -partition-size 256

启动一个叫avdName的模拟器，允许内存最大为256M


adb -d 当Android手机用USB连接计算机时可通过adb－d对该装置下命令
adb -e对正在运行的仿真器下指令
adb -s指定仿真器序号
adb dervices显示当前启动的仿真器装置序号
adb help显示adb指令用法
adb verson显示adb版本
adb install安装APK应用程序组件
adb push上传文件或目录（adb push 文件所在PC的位置即文件名 目的位置）
adb pull下载文件或目录（adb pull 文件所在手机的位置即文件名 目的位置）
adb shell进入Android系统命令行模式
adb logcat监控仿真器运行记录
adb bugreport生成adb出错报告
adb start－server启动adb服务器
adb kill－server关闭adb服务器
adb get－state取得adb服务器运行状态
adb get－serialno获得仿真器运行序号
adb forward tcp：port更改仿真器的网络TCP通信端口
