IRC 基本命令篇


查看命令
/help
命令使用帮助
/help 命令
连接服务器
/connect 服务器
改名字
/nick 新昵称
进入频道
/join #linuxba
离开频道
/part
退出服务器
/quit
和别人开小窗单独聊天
/query 昵称|#频道


--------------------------------------------------------------------------------
/JOIN 命令
【语法】
/join <#闲聊室> [该闲聊室的密码]
【描述】
用来加入某个闲聊室。如果该闲聊室设置了密码，你可以指定它。
--------------------------------------------------------------------------------
/PART 命令
【语法】
/part <#闲聊室> [退出的原因]
【描述】
用来退出某个闲聊室，在某些IRC服务器上，你还可以指定退出的原因。
--------------------------------------------------------------------------------
/LIST 命令
【语法】
/list [#闲聊室] [-MIN #] [-MAX #]
【描述】
用来列出服务器上的闲聊室名称(可以使用通配符)。如果不指定名称则列出当前服务器上的所有可用闲聊室；“-MIN
#”和“-MAX #”用来限定列出包含指定人数的闲聊室。
【举例】
列出包含2～100个人的所有闲聊室：/list -min 2 -max 100
--------------------------------------------------------------------------------
/MSG 命令
【语法】
/msg <别名|#闲聊室> <消息>
【描述】
用来向某人发出密聊话语，或者对某个闲聊室的所有人说话。
【举例】
假设你敲/msg TigTag
你好，那么TigTag就会在他的小窗口里看到你在说“你好”，而且这句话只有你跟TigTag才会看到；
假设你敲/msg #Chat 大家好，那么在#Chat中的全体成员都会看到你在说“大家好”。
【注意】
当用/MSG命令对某人发出密聊话语时，其作用与/QUERY相同。唯一的区别就是：使用/MSG命令时，自己这边不单独开个小窗口；而使用/QUERY命令时，双方都会各自开一个小窗口进行对侃。
--------------------------------------------------------------------------------
/ME 命令
【语法】
/me <动作>
【描述】
用来在当前闲聊室或者密聊小窗口做出动作。
【举例】
假设你在#Chat，那么当你敲/me 晕倒，#Chat的其他所有人就会看到你“晕倒”了。
--------------------------------------------------------------------------------
/QUERY 命令
【语法】
/query <别名> [密聊话语]
【描述】
用来向某人发出密聊话语。
【举例】
假设你敲/query TigTag
你好，那么你和TigTag双方都会各自弹出一个小窗口，“你好”这句话会同时出现在你跟TigTag各自的小窗口里，而且这句话只有你跟TigTag才会看到。
【注意】
当用/MSG命令对某人发出密聊话语时，其作用与/QUERY相同。唯一的区别就是：使用/MSG命令时，自己这边不单独开个小窗口；而使用/QUERY命令时，双方都会各自开一个小窗口进行对侃。
--------------------------------------------------------------------------------
/NOTICE 命令
【语法】
/notice <别名> <消息>
【描述】
用来向某人发出通告信息。与/MSG和/QUERY不同，这种通告信息不会在双方开小窗。
--------------------------------------------------------------------------------
/WHOIS 命令
【语法】
/whois <别名>
【描述】
用来获取某人的一些信息，如对方的真实名字，对方的IP，对方是何时登录IRC服务器的，等等。
--------------------------------------------------------------------------------
/WHO 命令
【语法】
/who [别名/地址|#闲聊室]
【描述】
用来获取某人的一些信息，如对方的IP；也可根据指定的IP找人；还可以列出指定闲聊室的人名。
【举例】
查找IP地址是127.0.0.1的人，用命令：/who 127.0.0.1
查找IP地址以192.168打头的人，用命令：/who 192.168.*
列出当前IRC服务器上的所有非隐藏的人，用命令：/who
【注意】
不是所有的IRC服务器都支持用/WHO命令找人
--------------------------------------------------------------------------------
/NICK 命令
【语法】
/nick <新别名>
【描述】
用来更改自己的别名。在高版本的mIRC里你也可以用/ANICK命令来更改自己的备用别名，格式同/NICK。
--------------------------------------------------------------------------------
/QUIT 命令
【语法】
/quit [退出连接的理由]
【描述】
用来退出与当前服务器的连接，并可以给出退出的理由。
【注意】
退出的理由只有那些在你退出的时候，与你在同一闲聊室的人才能看见。
--------------------------------------------------------------------------------
/AWAY 命令
【语法】
/away [暂时离开的原因]
【描述】
用来留下一条信息以说明你暂时要离开，你可以指定该信息。以后当某人再向你发送密聊话语或者对你做一个“/WHOIS”命令时，他/她就会看到你留下的信息并且得知你已经暂时离开了。
如果敲不带任何参数的/AWAY命令则可以解除离开状态。
--------------------------------------------------------------------------------
/ADMIN 命令
【语法】
/admin
【描述】
用来查询当前IRC服务器上Admin(即Administrator，IRC里最高级别的管理员)的相关信息
--------------------------------------------------------------------------------
/INFO 命令
【语法】
/info
【描述】
用来查询IRC服务器的信息，例如服务器的名称、版本号等等。
--------------------------------------------------------------------------------
/LUSERS 命令
【语法】
/lusers
【描述】
用来查询当前IRC服务器上的统计信息，例如当前的在线总人数、已经建立了多少个闲聊室等等。
--------------------------------------------------------------------------------
/MOTD 命令
【语法】
/motd
【描述】
用来查询当前IRC服务器上的今日信息(Message Of The Day)。
--------------------------------------------------------------------------------
/LINKS 命令
【语法】
/links
【描述】
用来解析当前的IRC有几个服务器，然后把解析到的结果放到一个单独的小窗口里。
--------------------------------------------------------------------------------
/NAMES 命令
【语法】
/names [#闲聊室]
【描述】
如果未指定闲聊室，则列出当前IRC服务器上的所有别名；否则只列出指定闲聊室的所有别名。
【注意】
如果某人利用/MODE命令对自己使用了“+i”（即设置为隐藏模式），则/NAMES将无法列出他的别名。
--------------------------------------------------------------------------------
/INVITE 命令
【语法】
/invite <别名> <#闲聊室>
【描述】
用来邀请某人到你指定的闲聊室。
--------------------------------------------------------------------------------
/TOPIC 命令
【语法】
/topic <#闲聊室> [新主题]
【描述】
用来更改指定闲聊室的聊天主题。
如果不指定新主题，则系统会告诉你指定闲聊室的当前主题。
--------------------------------------------------------------------------------
/KICK 命令
【语法】
/kick <#闲聊室> <别名> [踢他的原因]
【描述】
用来把某人从你指定的闲聊室赶出去。你可以指定赶他的理由。
【注意】
要使用/KICK命令，你必须在该闲聊室拥有帽子（也就是是主持人），或者是这个聊天服务器的管理员才可以。
--------------------------------------------------------------------------------
/MODE 命令
【语法】
/mode <#闲聊室|别名> [[+|-]参数]
【描述】
/MODE命令是一个强有力的命令，它使得一个闲聊室的主持人能够更改所属闲聊室以及该闲聊室成员的属性。
* 更改闲聊室的属性
参数　　　　　效果
b <别名>　 　禁止某人加入该闲聊室
i　　　　　 　把闲聊室设置成只有被邀请的人才能进入
l <人数>　 　限定进入该闲聊室的最大人数
m　 　　　　　旁听模式—只有主持人和被许可的人才能说话
n　　 　　　　是否接受从闲聊室外传来的信息(+n为不接受)
o <别名>　 　使指定的人也成为闲聊室的主持人，即给他/她@符号(帽子)
p　　　　　 　把闲聊室设置成私人房间
s　　　　 　　把闲聊室设置成隐藏
t　　　　 　　锁定主题—只有主持人才能更改它
k <密码>　 　为闲聊室设置密码—只有知道密码的人才能进来
* 更改用户的属性
参数　　　　　效果
i　　　　
使你变得不可见—如果你不在任何闲聊室里，而别人又不知道你的别名的话，他/她就看不到你
o　　　　
IRC管理员(IRC-OP)状态，/MODE命令只能取消该状态。要设置该状态必须用/OPER命令
s　　　　 　　是否接受服务器的通告(+s为接受)
v　　　　 　　允许某人在一个设置成旁听模式的闲聊室说话
w　　　　 　　是否接收WALLOPS信息
【注意】
要在某个闲聊室使用/MODE命令，大多数情况下，你必须在该闲聊室拥有帽子（也就是是主持人）才可以。
你只能更改某人在某个闲聊室的属性，而不能更改其在IRC服务器上的属性（自己除外）。
【举例】
使TigTag成为#Chat的主持人，用命令：/mode #Chat +o TigTag
使TigTag不再是#Chat的主持人，用命令：/mode #Chat -o TigTag
禁止TigTag进入#Chat，用命令：/mode #Chat +b TigTag
不再禁止TigTag进入#Chat，用命令：/mode #Chat -b TigTag
限定#Chat的最大人数是100，用命令：/mode #Chat +l 100
使TigTag在服务器上隐藏起来，用命令：/mode TigTag +i
……
* 如果要使多个人成为主持人，这里有个更快捷的方法：/mode #Chat +oooo nicka
nickb nickc nickd